# Experiment Parameters
root_dir: /mnt/projects/debruinz_project/forebacj/lightning_logs
config_name: config.yaml
experiment_name: Baseline
categories:
- 'donor_id'
- 'assay'
- 'dataset_id'
- 'cell_type'
- 'tissue'
- 'species'
merge_keys:
- z
expression_log_dir: /mnt/projects/debruinz_project/forebacj/3m_expressions
train_command:
  fit
  --data configs/data/local.yaml
  --model configs/model/moe_config.yaml
  --data.init_args.shared_conditionals '['assay']'
  --data.conditionals_directory /mnt/projects/debruinz_project/3m_expressions
  --model.init_args.module.init_args.vae.init_args.conditionals '['assay','dataset_id','donor_id','species']'
  --trainer.max_epochs 10
