# Experiment Parameters
root_dir: lightning_logs

config_name: config.yaml
experiment_name: experiment
run_name: version000

predict_dir: samples

model: configs/model/config.yaml
data: configs/data/local.yaml
trainer: configs/trainer/config.test.yaml

train_command: fit --trainer configs/trainer/config.test.yaml --model configs/model/config.yaml --data configs/data/local.yaml

categories: 
- 'donor_id'
- 'assay'
- 'dataset_id' 
- 'cell_type'

merge_keys:
- z