class_path: cmmvae.models.MOE_CMMVAEModel
init_args:
  kl_annealing_fn:
    class_path: cmmvae.modules.base.KLAnnealingFn
    init_args:
      kl_weight: 1
  record_gradients: false
  adv_weight: 1
  gradient_record_cap: 20
  module:
    class_path: cmmvae.modules.MOE_CMMVAE
    init_args:
      vaes:
        class_path: cmmvae.modules.ExpertVAEs
        init_args:
          vaes:
          - class_path: cmmvae.modules.MOE_CLVAE  # Shared VAE
            init_args:
              id: shared
              latent_dim: 128
              encoder_config:
                class_path: cmmvae.modules.base.FCBlockConfig
                init_args:
                  layers: [512, 256]
                  dropout_rate: 0.0
                  use_batch_norm: True
                  use_layer_norm: False
                  activation_fn: torch.nn.ReLU
                  return_hidden: True
              decoder_config:
                class_path: cmmvae.modules.base.FCBlockConfig
                init_args:
                  layers: [128, 256, 512]
                  dropout_rate: 0.0
                  use_batch_norm: False
                  use_layer_norm: False
                  activation_fn: torch.nn.ReLU
              # conditional_config:
              #   class_path: cmmvae.modules.base.FCBlockConfig
              #   init_args:
              #     layers:
              #     - 128
              #     dropout_rate: 0.0
              #     use_batch_norm: False
              #     use_layer_norm: True
              #     activation_fn: null
              # conditional_paths:
              #   assay: ./src/cmmvae/data/conditional_layers/unique_assays.csv
              # selection_order: null
          - class_path: cmmvae.modules.MOE_CLVAE  # Human VAE
            init_args:
              id: human
              latent_dim: 128
              encoder_config:
                class_path: cmmvae.modules.base.FCBlockConfig
                init_args:
                  layers: [512, 256]
                  dropout_rate: 0.0
                  use_batch_norm: True
                  use_layer_norm: False
                  activation_fn: torch.nn.ReLU
              decoder_config:
                class_path: cmmvae.modules.base.FCBlockConfig
                init_args:
                  layers: [128, 256, 512]
                  dropout_rate: 0.0
                  use_batch_norm: False
                  use_layer_norm: False
                  activation_fn: torch.nn.ReLU
              # conditional_paths:
              #   assay: ./src/cmmvae/data/conditional_layers/unique_assays.csv
              # selection_order: null
          - class_path: cmmvae.modules.MOE_CLVAE  # Mouse VAE
            init_args:
              id: mouse
              latent_dim: 128
              encoder_config:
                class_path: cmmvae.modules.base.FCBlockConfig
                init_args:
                  layers: [512, 256]
                  dropout_rate: 0.0
                  use_batch_norm: True
                  use_layer_norm: False
                  activation_fn: torch.nn.ReLU
              decoder_config:
                class_path: cmmvae.modules.base.FCBlockConfig
                init_args:
                  layers: [128, 256, 512]
                  dropout_rate: 0.0
                  use_batch_norm: False
                  use_layer_norm: False
                  activation_fn: torch.nn.ReLU
              # conditional_paths:
              #   assay: ./src/cmmvae/data/conditional_layers/unique_assays.csv
              # selection_order: null
      experts:
        class_path: cmmvae.modules.base.Experts
        init_args:
          experts:
          - class_path: cmmvae.modules.base.Expert
            init_args:
              id: human
              encoder_config:
                class_path: cmmvae.modules.base.FCBlockConfig
                init_args:
                  layers: [60664, 1024, 512]
                  dropout_rate: [0.1, 0.1]
                  use_batch_norm: True
                  use_layer_norm: False
                  activation_fn: torch.nn.ReLU
              decoder_config:
                class_path: cmmvae.modules.base.FCBlockConfig
                init_args:
                  layers: [512, 1024, 60664]
                  dropout_rate: 0.0
                  use_batch_norm: False
                  use_layer_norm: False
                  activation_fn: torch.nn.ReLU
          - class_path: cmmvae.modules.base.Expert
            init_args:
              id: mouse
              encoder_config:
                class_path: cmmvae.modules.base.FCBlockConfig
                init_args:
                  layers: [52417, 1024, 512]
                  dropout_rate: [0.1, 0.1]
                  use_batch_norm: True
                  use_layer_norm: False
                  activation_fn: torch.nn.ReLU
              decoder_config:
                class_path: cmmvae.modules.base.FCBlockConfig
                init_args:
                  layers: [512, 1024, 52417]
                  dropout_rate: 0.0
                  use_batch_norm: False
                  use_layer_norm: False
                  activation_fn: torch.nn.ReLU
      adversarials:
      - class_path: cmmvae.modules.base.FCBlockConfig
        init_args:
          layers: [256, 128, 64, 1]
          dropout_rate: 0.0
          use_batch_norm: False
          use_layer_norm: False
          activation_fn: torch.nn.Sigmoid
      ganh:
      - class_path: cmmvae.modules.base.FCBlockConfig
        init_args:
          layers: [60664, 1024, 256, 64, 1]
          dropout_rate: 0.0
          use_batch_norm: False
          use_layer_norm: False
          activation_fn: torch.nn.Sigmoid
      ganm:
      - class_path: cmmvae.modules.base.FCBlockConfig
        init_args:
          layers: [52417, 1024, 256, 64, 1]
          dropout_rate: 0.0
          use_batch_norm: False
          use_layer_norm: False
          activation_fn: torch.nn.Sigmoid
